### ISSUE TITLE
Wrong results when reprojecting data using GDAL 3.1.4 

### ISSUE THREAD

**Issue by bgsomeware** [Someware-fr/gdalmanylinux#1] opened 2020-12-22 17:35 UTC
Wrong coordinates are returned with the wheel file for GDAL 3.1.4.

This allows to reproduce the issue : 

```python
from osgeo import ogr, osr
import math
point = ogr.CreateGeometryFromWkt("POINT (-1.8748739 48.6876905)")
source_srs = osr.SpatialReference()
source_srs.SetFromUserInput('EPSG:4326')
dest_srs = osr.SpatialReference()
dest_srs.SetFromUserInput('EPSG:3948')
srs_transform = osr.CoordinateTransformation(source_srs, dest_srs)
point.Transform(srs_transform)
assert math.fabs(point.GetX() - 1341315.89056397) < 1E-8
assert math.fabs(point.GetY() - 7287808.08599262) < 1E-8
```

**Comment by jthiard** [comment] 2020-12-22 19:07
This seems unrelated to our wheel but to upstream OSGeo/gdal#1546
In short: GDAL >= 3.0 had some weird change in transform api concerning coordinates.

I tried your test changing it with

```python
from osgeo import ogr, osr
import math
point = ogr.CreateGeometryFromWkt("POINT (-1.8748739 48.6876905)")
source_srs = osr.SpatialReference()
source_srs.SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER)  # THIS FIX
source_srs.SetFromUserInput('EPSG:4326')
dest_srs = osr.SpatialReference()
dest_srs.SetFromUserInput('EPSG:3948')
srs_transform = osr.CoordinateTransformation(source_srs, dest_srs)
point.Transform(srs_transform)
assert math.fabs(point.GetX() - 1341315.89056397) < 1E-8
assert math.fabs(point.GetY() - 7287808.08599262) < 1E-8
```

And it works fine.

**Comment by jthiard** [comment] 2020-12-23 16:53
I close this one since fix will be in user code.
To avoid regressions on this with future versions og GDAL, I added a test in #5

**Closed by jthiard** 2020-12-23 16:53 UTC
Labels: bug, gdal-3
